import Head from "next/head";
import styles from "../styles/Events.module.scss";
import {Box, Flex, Heading, Image, Text} from "@chakra-ui/react";

export default function Events() {
    return (
        <>
            <Head>
                <title>Events | APAC</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.wrapper}>
                <section>
                    <Flex flexWrap={'wrap'}>
                        <Flex flexBasis={{lg: '60%', base: '100%'}} flexDirection={'column'} justify={'center'} align={'center'}>
                            <Heading as={'h1'}fontSize={{base: '3rem', md: '5rem'}} letterSpacing={'4px'}
                                     textTransform={"uppercase"} mb={'1rem'}>Our Events</Heading>
                            <Text fontSize={{base: '1.5rem', md: '2.5rem'}} mb={{base: '2rem', lg: 0}} textAlign={'center'}>The events that have been held by APAC</Text>
                        </Flex>
                        <Box flexBasis={{lg: '40%', base: '100%'}}>
                            <Image src={'/event/event.svg'} width={'80%'} mx={'auto'} alt={'Event SVG Picture'}/>
                        </Box>
                    </Flex>
                </section>
            </div>
        </>
    )
}